### PR TITLE
Modernized code

### PR DESCRIPTION
**Pull request by jkereako**
The main idea of this pull request is to bring the code up to modern Objective-C standards.
## Refactored code
- `instancetype` replaced the return type `id` in `init` methods.
- The property qualifier `strong` was removed because all properties are strong by default
- The  property qualifier `assign` was removed because it no longer has purpose
- The  property qualifier `unsafe_unretained` was replaced with `weak`
- Used dot-syntax wherever possible
- Added method prototypes to aid the static analyzer
- Removed un-implemented delegate methods

I turned on all warnings for XCode and enabled "treat warnings like errors" and compiled the project successfully.
## Changed coding style
- Changed the coding style to reflect the [NYT Objective-C style guide](https://github.com/NYTimes/objective-c-style-guide).

Originally, I was not going to submit a pull request so I went ahead and changed the coding style. But I figured what the hell and submitted a request anyway.

### CODE REVIEW

**Comment by sibljon** [comment]
Hi @jkereako,

Thanks for taking the time and effort to do a Pull Request.

I'll be looking into this when time permits; however, a couple thoughts in the meantime:
* I see the value in following a published Obj-C style guide, such as the one you mentioned.
* I'm not sure how this will fit in with the [2.0 development branch](https://github.com/hoteltonight/HTAutocompleteTextField/pull/41) that's currently open.

**Comment by jkereako** [comment]
@sibljon :
Thanks for the reply. As for your concern:
> I'm not sure how this will fit in with the 2.0 development branch that's currently open.

I had this in mind before I submitted the pull request:

>  The intention of this 2.0 release is to right the course, making this library both quicker to understand and easier to use... such as bug fixes, updates to support new iOS SDKs, and refactoring

The changes I made are in line with the NYT Objective-C style guide and the document [Adopting Modern Objective-C](https://developer.apple.com/library/ios/releasenotes/ObjectiveC/ModernizationObjC/AdoptingModernObjective-C/AdoptingModernObjective-C.html).

Both documents encourage brevity and clarity, (i.e. omitting `@synthesize` for `readwrite` properties and always use brackets in `if` statements, even one-liners).

**Comment by jkereako** [comment]
Closing!

I submitted this pull request over 1 year ago and there has not been any movement on this or the project in general.

Since I created this pull request, I learned Swift ported this library to Swift. Check out [AutocompleteTextField](https://github.com/jkereako/AutocompleteTextField).

**Comment by sibljon** [comment]
:+1:

**Pull request closed without merging**
